version: '3'
services:
  react-app:
    build: 
      context: ./language_learning_client
      dockerfile: Dockerfile.dev 
    ports:
      - "3000:3000"
    volumes:
      - ./language_learning_client/src:/app/src
      - ./language_learning_client/public:/app/public
    depends_on:
      - node-app
    environment:
      - REACT_APP_NODE_APP_URL=http://node-app:3001
      - CHOKIDAR_USEPOLLING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  node-app:
    build: .
    ports:
      - "5001:3001"
    depends_on:
      - db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d/