services:
  react-app:
    build: ./language_learning_client
    ports:
      - "3000:3000"
    depends_on:
      - node-app
    environment:
      - REACT_APP_NODE_APP_URL=http://node-app:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  node-app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d/